Update patch set 5
Patch Set 5: Code-Review+2

docker run --rm -i -t -v $(pwd)/..:/code:ro janus-client-jessie:latest bash
root@14881551aa93:/code# cd /code && ./t/testrunner
JFYI, usage: ./t/testrunner [<output_directory>] [junit]
npm WARN package.json janus-client@1.0.0 No description
npm WARN package.json janus-client@1.0.0 No repository field.
npm WARN package.json janus-client@1.0.0 No README data
uuid@2.0.3 node_modules/uuid

bluebird@3.4.6 node_modules/bluebird

ws@1.1.1 node_modules/ws
├── options@0.0.6
└── ultron@1.0.2

debug-logger@0.4.1 node_modules/debug-logger
└── debug@2.2.0 (ms@0.7.1)

chai@3.5.0 node_modules/chai
├── assertion-error@1.0.2
├── type-detect@1.0.0
└── deep-eql@0.1.3 (type-detect@0.1.1)

lodash@4.16.4 node_modules/lodash

mocha@3.1.2 node_modules/mocha
├── diff@1.4.0
├── browser-stdout@1.3.0
├── escape-string-regexp@1.0.5
├── growl@1.9.2
├── json3@3.3.2
├── debug@2.2.0 (ms@0.7.1)
├── supports-color@3.1.2 (has-flag@1.0.0)
├── commander@2.9.0 (graceful-readlink@1.0.1)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── lodash.create@3.1.1 (lodash._isiterateecall@3.0.9, lodash._basecreate@3.0.3, lodash._baseassign@3.2.0)
└── glob@7.0.5 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, once@1.4.0, inflight@1.0.6, minimatch@3.0.3)

> janus-client@1.0.0 test /code_rw
> mocha -R nyan --delay

 0   -__,------,
 1   -__|  /\_/\ 
 0   -_~|_( x .x) 
     -_ ""  "" 

  0 passing (10ms)
  1 failing

  1) Client should create a janus client:
     TypeError: janus.on is not a function
      at Context.<anonymous> (test/clientSpec.js:40:19)



npm ERR! Test failed.  See above for more details.
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

Patch-set: 5
Label: Code-Review=+2